version: "3"
services:
    app:
        build: ./php5-fpm
        links:
            - db
        restart: always
        volumes:
            - ./php5-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./app/current/public:/var/www
    nginx:
        image: nginx:1.13
        links:
            - app
        ports:
            - 80:80
        restart: always
        volumes:
            - ./app/current/public:/var/www
            - ./log/nginx/:/var/log/nginx
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    db:
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "33062:3306"
        restart: always
        volumes:
            - db-data:/var/lib/mysql
            - ./backup:/var/backup
volumes:
    db-data:
        driver: local
